### ISSUE TITLE
when running importRez() error message with rjson::fromJSON()

### ISSUE THREAD

**Issue by gtroiani** [rezonators/rezonateR#114]
I am following the demo on the rezonateR website and ran this code:

`library(rezonateR)`
`path = system.file("extdata", "virginia-library-20766.rez", package = "rezonateR")`
`layerRegex = list(
  track = list(field = "trailLayer", regex = c("clausearg", "discdeix"), names = c("clausearg", "discdeix", "refexpr")),
  chunk = list(field = "chunkLayer", regex = c("verb", "adv", "predadj"), names = c("verb", "adv", "predadj", "refexpr")))`
`myRez = importRez(path, layerRegex = layerRegex, concatFields = c("word", "wordWylie"))`

I got this error and cannot figure out how to solve it:

> Error in rjson::fromJSON(file = paths) : 
>   attempt to set index 1/1 in SET_STRING_ELT
> In addition: Warning message:
> In file(con, "r") :
>   file("") only supports open = "w+" and open = "w+b": using the former

**Comment by kayaulai** [comment]
Could you tell me what the value of `path` is? It appears that it may be an issue with the path.

If the `path` is problematic, could you try looking for the path of the `rezonateR` package on your computer and replace `path` with `(path to rezonateR)\extdata\virginia-library-20766.rez`?

**Comment by gtroiani** [comment]
Ok I tried the following and it worked:

`(path_to_rezonateR)/rezonateR/extData/virginia-library-20766.rez`

But I had no `inst` folder, so when I dropped it, the code worked. And I have `extdata` and `extData` folders. The `virginia-library-20766.rez` is located in `extData`.

In case it helps: I am using Ubuntu 22.04; R 4.1.2

**Comment by kayaulai** [comment]
Note: it's extdata on my computer but extData on GitHub for some reason. need to figure out why and fix.
